### ISSUE TITLE
Linux Terminal Version?

### ISSUE THREAD

**Issue by Shazgul** [Miouss/wwe-dl#18]
Hey, will there be an Linux Terminal Version, so that i can use this remote on my Ubuntu Server without always going into Remote Control :D?

**Comment by Miouss** [comment]
Hello, sorry i wasn't paying attention to my notification.

To be honest, I don't know, the development is suspended until i finish others projects.

**Comment by Miouss** [comment]
My aim with this software is precisely to open it towards any providers, I'll have to make the correct structure to have to just add each API calls necessary to get the media from any provider.
